version: '3.9'

services:
  # =========================
  # Istanze del servizio users
  # =========================
  user-service-1:
    build: ./user-service
    container_name: user-service-1
    environment:
      - SERVICE_NAME=user-service
      - INSTANCE_ID=user-service-1
    volumes:
      - users-data:/data
    networks:
      - backend
    expose:
      - "5000"

  user-service-2:
    build: ./user-service
    container_name: user-service-2
    environment:
      - SERVICE_NAME=user-service
      - INSTANCE_ID=user-service-2
    volumes:
      - users-data:/data
    networks:
      - backend
    expose:
      - "5000"

  # =========================
  # istanze del servizio orders
  # =========================
  orders-service-1:
    build: ./order-service
    container_name: orders-service-1
    environment:
      - SERVICE_NAME=orders-service
      - INSTANCE_ID=orders-service-1
    volumes:
      - orders-data:/data
    networks:
      - backend
    expose:
      - "5000"

  orders-service-2:
    build: ./order-service
    container_name: orders-service-2
    environment:
      - SERVICE_NAME=orders-service
      - INSTANCE_ID=orders-service-2
    volumes:
      - orders-data:/data
    networks:
      - backend
    expose:
      - "5000"
  # =========================
  # istanza servizio monitoraggio stato istanze
  # =========================   
  health-check:
    build: ./health-check
    container_name: health-check
    depends_on:
      - user-service-1
      - orders-service-1
    networks:
      - backend

# =========================
# NGINX API Gateway
# =========================
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - user-service-1
      - user-service-2
      - orders-service-1
      - orders-service-2
# =========================
# Network interna
# =========================
networks:
  backend:
    driver: bridge

# =========================
# Volumi
# =========================

volumes:
  orders-data:
  users-data: